### ISSUE TITLE
Error: Invalid XML-RPC message

### ISSUE THREAD

**Issue by zining3235** [szx741/push-markdown#1]
**描述该错误**
简明扼要地描述一下这个bug是什么。
配置完成后，发布出现错误
![Snipaste_2022-10-22_18-07-06](https://user-images.githubusercontent.com/73809000/197333693-4570dc3b-a76a-4327-aac4-39b1c2ae565b.png)

**要重现**
重现该行为的步骤。
1. 转到"..."。
2. 点击'....'。
3. 向下滚动到'....'
4. 看到错误

**预期的行为**
简明扼要地描述你期望发生的情况。

**屏幕截图**
如果适用，添加屏幕截图以帮助解释你的问题。

**额外的背景**
在这里添加关于问题的任何其他背景。

**Comment by szx741** [comment]
你好，下载的哪个版本，这个问题比较难以排查，如果是1.x版本的，先卸载，再去download.szx.life下载最新版，然后填完配置之后，点击帮助，查看示例文档，发布，看看还有没有问题

**Comment by szx741** [comment]
我看你的博客打开还有点问题，是不是博客还没配置好？
