### ISSUE TITLE
URL的问题

### ISSUE THREAD

**Issue by ifp1090** [szx741/push-markdown#2]
您好！我使用了您开发的push－markdown工具，成功实现了文章上传到WordPress，谢谢！
但同时遇到了一个问题：我的每篇文章都匹配了WordPress中的“特色图片”以及“页面页眉图片”，参见图示：

![](https://pbox.online/202304061240377.png)

上述两个部分的图片分别显示在主页和文章点开后的内页：

特色图片首页显示：

![](https://pbox.online/202304061243741.png)

页面点开之后的顶图显示：

![](https://pbox.online/202304061244243.png)

这两张图可否通过上传的方式同步实现？

如果页面页眉图片无法实现，可否实现“特色图片”这个功能？比如通过类似markdown的图片外链方式搞定？

以上，期待您的指导，谢谢！

**Comment by szx741** [comment]
你好，文章特色图片我尝试了一下，这个问题可以解决，我将会在下个版本进行更新，但是由于数据结构会进行变动，需要重新导入文章配置，赖我没有一次性做好结构配置。
页面页眉图片这个选项我没有找到，我不知道是不是你主题或者插件的功能。我估计这个功能是无法实现的，我的所有上传功能都是通过wordpress提供的[xmlrpc](https://codex.wordpress.org/XML-RPC_MetaWeblog_API)功能来实现的，因为特色头图可以在newPost的时候添加一个wp_post_thumbnail属性，就可以设置特色头图。页面页眉头图如果是插件或者主题实现的，那么官方newPost的话应该是没有这个字段的，所以无法实现这个功能，只能说抱歉了。

**Comment by ifp1090** [comment]
好的，非常感谢！期待您的更新！祝好！

**Comment by ifp1090** [comment]
对了，您这边未来可有增加mac端的发布计划？

**Comment by szx741** [comment]
没有嗷，主要原因是穷哈。大概率是可以在mac下面运行的，electron是跨平台的，我也没有针对win进行特殊优化，之前v1.x的版本叫别人打包过mac版本的，是可以运行的。因为我没有mac，所以无法打包，如果你想弄mac版本的话，可以自己打包试试看。
mac平台有个收费的应用，叫MWeb，是个写markdown的软件，也可以上传到wordpress等平台，如果你财力雄厚的话可以试试那个软件。

**Comment by ifp1090** [comment]
我还是等您的Win版更新吧！支持您的努力！如果有打赏也行 ：）

**Comment by szx741** [comment]
已经更新啦，在软件里帮助-检查更新就有了，会在后台静默下载，由于服务器水管比较小，大概需要2分钟左右的时间下载。
我在这说明一下怎么使用，由于数据结构进行了一个替换，所以需要你在设置-打开设置文件中，去除post和media两个字段，再重新从剪切板导入，导入这部分的内容也变了，变成六个字段了，具体可以看本仓库下docs/使用教程。
上传特色图片的话，只需要在文本上面的yaml格式中，加入thumbnail参数以及你的本地图片路径，就可以把图片上传上去并自动设置为特色图片。如果你想换张头图的话，只需要改个本地图片路径就行了，然后再重新上传，就能更换了。
因为你还有一个页面页眉图片的需求，虽然设置图片我无法帮你做到，但是上传图片这步可以帮你做一下。同样在文本上面，加入other_images字段，这个字段是个数组类型，所以你可以写上多张图片的路径，这样子就可以跟随文章一块上传上去。

**Comment by ifp1090** [comment]
您好！谢谢您的更新！
我刚刚测试了一下，发现按照您的格式，可以将特色图片上传到wordpress后台，但是却不能被识别为特色图片，请问这是怎么回事？
![](https://pbox.online/202304101327339.png)
另外我想问一下，特色图片可否不通过图片路径的方式上传，而是通过类似markdown显示的图片外链的方式发布，而在wordpress上的特色图片显示出来？

**Comment by szx741** [comment]
不能吗？不能的话说不定是插件的问题，要么是我有什么插件支持这个功能，要么是你插件改动了这个功能，你的页面页眉图片可能对这部分功能进行了更改，你试试停用插件看看。

**Comment by szx741** [comment]
另外你说的图片外链的方式，这种方式不行，因为xmlrpc的wp_thumbnail_id是只能指定wordpress里面媒体图片的ID号

**Comment by ifp1090** [comment]
我现在尝试通过另外一个网站来测试一下，但是奇怪始终发布不成功，一直提示文章ID无效。

**Comment by szx741** [comment]
你换了新的网站？我的锅，如果你添加了第二个网站，那么他的文章ID还会保留着第一个网站的ID，所以你发布是相当于用其他网站的文章ID进行填充

**Comment by ifp1090** [comment]
好的。无意间测出来一个小bug，哈哈！

**Comment by szx741** [comment]
我重新弄了，你去http://download.szx.life/push-markdown 下载最新版的试试看。我因为没有多个博客网站，所以多站点发布从来没有测试过，很难说没有新的问题，靠你帮忙测试了

**Comment by ifp1090** [comment]
抱歉现在才回复。刚刚测试发现是没问题的，非常感谢哈！对了您在什么地方？如果有可能的话，可以把我的古董Mac借给你来开发一个mac版本的终端就好了：）再次感谢！

**Comment by szx741** [comment]
好的，没问题就行了。哈哈，以后有机会我再入手一个mac吧，马上就快要毕业了，等赚点钱买个mac。其实你自己就可以编译，安装nodejs和pnpm，下载我的源码，然后 pnpm i 安装依赖，再 pnpm run mac，就按理能说可以打包一个mac版本的安装包了。

**Comment by ifp1090** [comment]
谢谢！这个挑战我想尝试一下，但我基本上是小白级。我刚刚搜索了一个你提到的关于pnpm i的操作指南：https://blog.xiaolong0418.com/blogs/4           
请问是这样的 一步一步的操作步骤吗？

**Comment by szx741** [comment]
在命令终端中，在这个仓库代码的根目录下运行 pnpm install 或者 pnpm i （简写版），就会安装软件所需要的依赖包，如果没有报error错误的话，你可以再运行 pnpm run watch，看看能否直接编译成功，如果成功其实会直接弹出push-markdown的界面（启动时需要关闭自己安装的push-markdown，否则会启动不了，因为只允许一个push-markdown出现）。如果使用没有问题，再运行pnpm run mac试试看，如果成功，会在dist目录下生成mac的安装包吧？mac的打包配置选项在.electron-builder.config.js文件里面，配置选项可以参考官网https://www.electron.build/configuration/mac 。如果还是不行的话，建议放弃，或者看看项目整体架构的模板代码https://github.com/cawa-93/vite-electron-builder ，我就是在这个模板代码的基础上写的。

**Comment by ifp1090** [comment]
你好！谢谢你的驱动！

我通过ChatGPT的指导，成功将push-markdown打包成了一个mac安装包！

但是有一个问题，我发现这款软件的图标显示不对，ChatGPT表示要重新设置符合macOS的图标，我已经设置好了（.icns格式），也放到了public目录下替换了原来的app.ico文件。但是打包出来的文件并不是这个图标。

我问ChatGPT，它表示要更改electron-bulider的配置文件，它让我搜索这个.js文件，但是我没有搜索到，请问这一步应该如何处理？

谢谢！

![image-20230426111520836](http://pbox.online/202304261115859.png)

**Comment by ifp1090** [comment]
你好！谢谢你的驱动！

我通过ChatGPT的指导，成功将push-markdown打包成了一个mac安装包！并在mac上测试通过！

![image-20230426142827992](http://pbox.online/202304261428014.png)

打包的软件地址【[[下载地址](https://www.123pan.com/s/QKtA-s2xpA.html)](https://www.123pan.com/s/QKtA-s2xpA.html)】

再次感谢您的支持与付出！

祝好！

**Comment by ifp1090** [comment]
你好！谢谢你的驱动！

我通过ChatGPT的指导，成功将push-markdown打包成了一个mac安装包！并在mac上测试通过！

![image-20230426142827992](http://pbox.online/202304261428014.png)

打包的软件地址  [**[下载地址](https://www.123pan.com/s/QKtA-s2xpA.html)**](https://www.123pan.com/s/QKtA-s2xpA.html)

再次感谢您的支持与付出！

祝好！

**Comment by szx741** [comment]
不好意思，没有及时看到，非常高兴你成功打包了。如果你对仓库内容进行了修改，可以给我发一个pull request，我合并一下，这样子以后打包mac就会方便一点。

**Comment by ifp1090** [comment]
好的，我完成了，你看一下？

另外上次我提到的页面的文章顶图设置，您可否帮我看一下这个设置是否可以自动化？

我目前发现，如果我按照pushmarkdown默认推送，这张特色图片就会被自动设置为该文章的顶图。

![image-20230427102714008](http://pbox.online/202304271027040.png)



示例：http://mread.top/1329.html

而我每次都是手动进入后台将其调整为我需要的图片。

但我觉得觉得这个地方貌似也可以自动化实现？

因为上传的是特色图片，这个地方自动化被设置为「特色图片」，那是否存在一定的图片路径对应关系？即：

- 特色图片 = A
- 文章顶图 = B
- 默认设置： A = B

这样就会将上传上去的图片自动对应。

那么是否可能作某种改动，将B的路径找到，也通过上传的方式实现。

那么这样就不需要每次都是手动调整更改了？

每次我更改这个地方都需要在这里去改：

![image-20230427103207441](http://pbox.online/202304271032464.png)

所以会有一些不方便。

您可否就这个问题做一些分析？

为了便于您查看，我在网站帮您添加了一个角色您可以试试看？

> ID: tese
>
> PW：china@ifp790
>
> Web：mread.top/admin

应该也可以通过PushMarkdown来上传，配置如下：

> 名称：mread
>
> URL：http://mread.top/xmlrpc.php

期待回复，谢谢！

**Comment by szx741** [comment]
谢谢你的pr，我已经合并了。
你说的这个，我还是无能为力，我再讲清楚一点。原生的wordpress并没有设置页面页眉图片的选项。也就是页面页眉图片就是特色图片，没有区分两者，只有一个字段wp_thumbnail。
![image](https://user-images.githubusercontent.com/36142570/234756881-ea2294b9-23ba-4839-98b5-c2bc8f432970.png)
我看你用的wpbakery这个页面生成器，他应该是自己做了很多调整，包括可以单独设置页面页眉图片。由于wordpress自带的xmlrpc在发布文章的时候，只能设置一个wp_thumbnail_id，也就是设置哪张图片作为特色图片。因为你的设置页面页眉图片是wpbakery自定义的字段，所以我无法通过任何接口来设置这个页面页眉图片。虽然很抱歉，但是这部分内容只能你自己手动设置了。

**Comment by ifp1090** [comment]
好的没关系哈，非常感谢你的支持！

**Comment by ifp1090** [comment]
你好！我遇到了一个奇怪的问题，就是我通过终端发布文章，终端显示发送成功，但是我在网站上却找不到我刚发的这篇文章。我尝试换一台电脑来尝试，也是相同的问题！都是发送成功但却找不到文章！不知道这是咋回事？

**Comment by szx741** [comment]
不好意思，最近没有看邮箱，你先看看博客的地址是否配置对的。如果发表成功的话，会返回postid，你可以打开设置文件，看看你这篇文章url的postid是否存在，如果存在，那么就说明博客已经成功创建新的文章了，这个id是wordpress创建成功之后才会返回来的。你可以看看是不是设置了什么，比如变成草稿，或者到回收站了。我自己这边再发布了一篇新的，是正常的。还有一种可能是你配置了多个博客地址，因为这块我没有测试过，可能依旧有bug。也有可能是你的主题插件进行了更新，对某些部分进行了更改。
